In [2]:
import fasttext
from huggingface_hub import hf_hub_download
from carte_ai import Table2GraphTransformer

/Users/k.m.tatarov/Desktop/course/educational-trajectories/venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Matplotlib is building the font cache; this may take a moment.


In [5]:
import pandas as pd

df = pd.DataFrame({
    "A": [1, 2, 3],
    "B": ["x", "y", "z"]
})

# 1) как список словарей:
payload = df.to_dict(orient="records")
df

A  B
0  1  x
1  2  y
2  3  z

In [6]:
payload

[{'A': 1, 'B': 'x'}, {'A': 2, 'B': 'y'}, {'A': 3, 'B': 'z'}]

In [4]:
pd.DataFrame(payload)

A  B
0  1  x
1  2  y
2  3  z

In [4]:
import pandas as pd
from carte_ai.data.load_data import *

df = pd.DataFrame({
    'student_id': ['s1','s2','s3','s4','s5','s6','s7','s8'],
    'quarter_1': [4, 3, 2, np.nan, 5, 3, 4, 4],
    'quarter_2': [4, 3, 3, 4, 5, 4, 5, 3],
    'semester':  [5, 2, np.nan, 4, 5, 4, 4, 4],
    'year':      [3, 4, 5, 5, np.nan, 4, 5, 3],
})
df

student_id  quarter_1  quarter_2  semester  year
0         s1        4.0          4       5.0   3.0
1         s2        3.0          3       2.0   4.0
2         s3        2.0          3       NaN   5.0
3         s4        NaN          4       4.0   5.0
4         s5        5.0          5       5.0   NaN
5         s6        3.0          4       4.0   4.0
6         s7        4.0          5       4.0   5.0
7         s8        4.0          3       4.0   3.0

In [29]:
df.iloc[:, 0].notna()

0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
Name: student_id, dtype: bool

In [33]:
p = df.iloc[:, 1][df.iloc[:, 1].notna()]

k = p

In [84]:
Path().absolute()

PosixPath('/Users/k.m.tatarov/Desktop/course/educational-trajectories/production/streamlit-service')

In [100]:
import os
print(os.path.exists("../../production/models/CARTE/cc.en.300.bin"))  # должен вернуть True

True


In [78]:
model_path

PosixPath('/Users/k.m.tatarov/Desktop/course/educational-trajectories/production/models/CARTE/cc.en.300.bin')

In [69]:
df.replace({np.nan: None})

student_id quarter_1 quarter_2  year
0         s1       3.0       5.0   3.0
1         s2       3.0       2.0   4.0
2         s3       2.0      None   5.0
3         s4      None       4.0   5.0
4         s5       5.0       5.0  None
5         s6       3.0       4.0   4.0
6         s7       4.0       4.0   5.0
7         s8       4.0       4.0   3.0

In [70]:
type(df.replace({np.nan: None}).iloc[3,1])

NoneType

In [16]:
df.columns[2]

'quarter_2'

In [10]:
df.iloc[:, 1].isna()

0    False
1    False
2    False
Name: B, dtype: bool

In [70]:
df.shape[1]

5

In [5]:
df_cl = df.drop('student_id',axis=1)

In [6]:
df_cl.isna().sum()

quarter_1    1
quarter_2    0
semester     1
year         1
dtype: int64

In [102]:
df

student_id  quarter_1  quarter_2  year
0         s1        3.0        5.0   3.0
1         s2        3.0        2.0   4.0
2         s3        2.0        NaN   5.0
3         s4        NaN        4.0   5.0
4         s5        5.0        5.0   NaN
5         s6        3.0        4.0   4.0
6         s7        4.0        4.0   5.0
7         s8        4.0        4.0   3.0

In [107]:
np.array(t)

array([3])

In [104]:
t = df.index[df.iloc[:, 1].isna()]
t

Index([3], dtype='int64')

In [115]:
df.iloc[[1,2,4], 1] = [111,222,333]

In [118]:
np.round([1.234,43.2,5,376.3],2)

array([  1.23,  43.2 ,   5.  , 376.3 ])

In [117]:
df

student_id  quarter_1  quarter_2  year
0         s1        3.0        5.0   3.0
1         s2      111.0        2.0   4.0
2         s3      222.0        NaN   5.0
3         s4        NaN        4.0   5.0
4         s5      333.0        5.0   NaN
5         s6        3.0        4.0   4.0
6         s7        4.0        4.0   5.0
7         s8        4.0        4.0   3.0

In [13]:
df_cl.iloc[:1]

quarter_1  quarter_2  semester  year
0        4.0          4       5.0   3.0

In [2]:
import fasttext
from huggingface_hub import hf_hub_download
from carte_ai import Table2GraphTransformer

#model_path = hf_hub_download(repo_id="hi-paris/fastText", filename="cc.en.300.bin")

preprocessor = Table2GraphTransformer(fasttext_model_path="/Users/k.m.tatarov/Desktop/course/educational-trajectories/production/models/CARTE/cc.en.300.bin")
#X_test = preprocessor.transform(X_test)

/Users/k.m.tatarov/Desktop/course/educational-trajectories/venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [101]:
import os

# Директория скрипта
BASE_DIR = os.path.dirname(__file__)

# Путь к файлу в подпапке
file_path = os.path.join(BASE_DIR, "data", "my_file.txt")

# Абсолютный путь
file_path = os.path.abspath(file_path)

print(file_path)
print(os.path.exists(file_path))


NameError: name '__file__' is not defined

In [9]:
preprocessor

Table2GraphTransformer(fasttext_model_path='/Users/k.m.tatarov/Desktop/course/educational-trajectories/production/models/CARTE/cc.en.300.bin')

In [ ]:
model_path

'/Users/k.m.tatarov/.cache/huggingface/hub/models--hi-paris--fastText/snapshots/96f36288c269c029268ee44f370791679a906117/cc.en.300.bin'

In [10]:
df_cl_1 = df_cl.drop("quarter_1",axis=1)
df_cl_1_train = df_cl_1[df_cl["quarter_1"].notna()]
df_cl_1_test = df_cl_1[df_cl["quarter_1"].isna()]

In [11]:
X_train = preprocessor.fit_transform(df_cl_1_train, y=df_cl['quarter_1'][df_cl["quarter_1"].notna()])


In [12]:
X_test = preprocessor.transform(df_cl_1_test)

In [15]:
from carte_ai import CARTERegressor, CARTEClassifier

# Define some parameters
fixed_params = dict()
fixed_params["num_model"] = 3 
fixed_params["disable_pbar"] = True
fixed_params["random_state"] = 0
fixed_params["device"] = "cpu"
fixed_params["n_jobs"] = 10
fixed_params["pretrained_model_path"] = "/Users/k.m.tatarov/Desktop/course/educational-trajectories/production/models/CARTE/carte_weights.pt"


# Define the estimator and run fit/predict

estimator = CARTERegressor(**fixed_params) # CARTERegressor for Regression
estimator.fit(X=X_train, y=df_cl['quarter_1'][df_cl["quarter_1"].notna()])

/Users/k.m.tatarov/Desktop/course/educational-trajectories/venv/lib/python3.11/site-packages/carte_ai/src/carte_estimator.py:140: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler()
/Users/k.m.tatarov/Desktop/course/educational-trajectories/venv/lib/python3.11/site-packages/carte_ai/src/carte_estimator.py:140: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler()
/Users/k.m.tatarov/Desktop/course/educational-trajectories/venv/lib/python3.11/site-packages/torch/amp/grad_scaler.py:136: UserWarning: torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.
  warnings.warn(
/Users/k.m.tatarov/Desktop/course/educational-trajectories/venv/lib/python3.11/site-packages/torch/amp/grad_scaler.py:136: UserWarning: torch.cuda.amp.GradScaler is enabled, but CUDA is not available.

CARTERegressor(n_jobs=10, num_model=3,
               pretrained_model_path='/Users/k.m.tatarov/Desktop/course/educational-trajectories/production/models/CARTE/carte_weights.pt')

In [52]:
X_test+X_test

[Data(x=[4, 300], edge_index=[2, 6], edge_attr=[6, 300], y=[0], g_idx=0),
 Data(x=[4, 300], edge_index=[2, 6], edge_attr=[6, 300], y=[0], g_idx=0)]

In [17]:
X_test

[Data(x=[4, 300], edge_index=[2, 6], edge_attr=[6, 300], y=[0], g_idx=0)]

In [24]:
df.iloc[:, 1].isna()

0    False
1    False
2    False
3     True
4    False
5    False
6    False
7    False
Name: quarter_1, dtype: bool

In [18]:
y_pred = estimator.predict(X_test+X_test)

# Obtain the r2 score on predictions

# score = r2_score(y_test, y_pred)
# print(f"\nThe R2 score for CARTE:", "{:.4f}".format(score))

In [20]:
type(y_pred)

numpy.ndarray

In [58]:
X_train

[Data(x=[4, 300], edge_index=[2, 6], edge_attr=[6, 300], y=[1], g_idx=0),
 Data(x=[4, 300], edge_index=[2, 6], edge_attr=[6, 300], y=[1], g_idx=1),
 Data(x=[3, 300], edge_index=[2, 4], edge_attr=[4, 300], y=[1], g_idx=2),
 Data(x=[3, 300], edge_index=[2, 4], edge_attr=[4, 300], y=[1], g_idx=3),
 Data(x=[4, 300], edge_index=[2, 6], edge_attr=[6, 300], y=[1], g_idx=4),
 Data(x=[4, 300], edge_index=[2, 6], edge_attr=[6, 300], y=[1], g_idx=5),
 Data(x=[4, 300], edge_index=[2, 6], edge_attr=[6, 300], y=[1], g_idx=6)]

In [55]:
estimator.predict(X_train)

array([3.5307648, 3.1662204, 2.5997758, 3.864043 , 3.1305125, 3.6734254,
       3.6198165], dtype=float32)

In [68]:
import numpy as np
from carte_ai import CARTERegressor
from numpy.exceptions import AxisError

orig_predict = CARTERegressor.predict

def patched_predict(self, X):
    try:
        return orig_predict(self, X)
    except AxisError:
        print('WE HERE')
        # восстанавливаем скалярное предсказание
        return np.array([self.model_list_[0].predict(X)[0]])

CARTERegressor.predict = patched_predict

print(orig_predict)
# Теперь просто:
y_pred = estimator.predict(X_test)


<function patched_predict at 0x3101e16c0>



KeyboardInterrupt



In [1]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('educational-trajectories/temp.csv', sep=',', 
                 header = None)

df

In [3]:
from carte_ai import Table2GraphTransformer, CARTERegressor

/Users/k.m.tatarov/Desktop/course/educational-trajectories/venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [ ]:
fixed_params = dict()
fixed_params["num_model"] = 3
fixed_params["disable_pbar"] = False
fixed_params["random_state"] = 0
fixed_params["load_pretrain"] = True
fixed_params["device"] = "cpu"
fixed_params["n_jobs"] = 10
fixed_params["pretrained_model_path"] = "educational-trajectories/production/models/CARTE/carte_weights.pt"

estimator = CARTERegressor(**fixed_params)

In [ ]:
preprocessor = Table2GraphTransformer(fasttext_model_path="educational-trajectories/production/models/CARTE/cc.en.300.bin")

In [ ]:
import pandas as pd

df = pd.read_csv("educational-trajectories/temp.csv")
df

student_id  quarter_1  quarter_2  semester  year
0         s1        4.0          4       5.0   3.0
1         s2        3.0          3       2.0   4.0
2         s3        2.0          3       NaN   5.0
3         s4        NaN          4       4.0   5.0
4         s5        5.0          5       5.0   NaN
5         s6        3.0          4       4.0   4.0
6         s7        4.0          5       4.0   5.0
7         s8        4.0          3       4.0   3.0

In [12]:
df['year']

0    3.0
1    4.0
2    5.0
3    5.0
4    NaN
5    4.0
6    5.0
7    3.0
Name: year, dtype: float64

In [13]:
X_graph_train = preprocessor.fit_transform(df.drop(['year'], axis=1), y=df['year'])

In [17]:
estimator.fit(X_graph_train, df['year'])

/Users/k.m.tatarov/Desktop/course/educational-trajectories/venv/lib/python3.11/site-packages/carte_ai/src/carte_estimator.py:140: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler()
/Users/k.m.tatarov/Desktop/course/educational-trajectories/venv/lib/python3.11/site-packages/carte_ai/src/carte_estimator.py:140: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler()
/Users/k.m.tatarov/Desktop/course/educational-trajectories/venv/lib/python3.11/site-packages/torch/amp/grad_scaler.py:136: UserWarning: torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.
  warnings.warn(
/Users/k.m.tatarov/Desktop/course/educational-trajectories/venv/lib/python3.11/site-packages/torch/amp/grad_scaler.py:136: UserWarning: torch.cuda.amp.GradScaler is enabled, but CUDA is not available.

CARTERegressor(disable_pbar=False, n_jobs=10, num_model=3,
               pretrained_model_path='/Users/k.m.tatarov/Desktop/course/educational-trajectories/production/models/CARTE/carte_weights.pt')

In [19]:
len(estimator.model_list_)

3

In [39]:
estimator.model_list_[0]

CARTE_NN_Model(
  (ft_base): CARTE_Base(
    (initial_x): Sequential(
      (0): Linear(in_features=300, out_features=300, bias=True)
      (1): GELU(approximate='none')
      (2): LayerNorm((300,), eps=1e-05, elementwise_affine=True)
    )
    (initial_e): Sequential(
      (0): Linear(in_features=300, out_features=300, bias=True)
      (1): GELU(approximate='none')
      (2): LayerNorm((300,), eps=1e-05, elementwise_affine=True)
    )
    (layers): ModuleList()
    (read_out_block): CARTE_Block(
      (g_attn): CARTE_Attention(
        (lin_query): Linear(in_features=300, out_features=300, bias=False)
        (lin_key): Linear(in_features=300, out_features=300, bias=False)
        (lin_value): Linear(in_features=300, out_features=300, bias=False)
      )
      (linear_net_x): Sequential(
        (0): Linear(in_features=300, out_features=300, bias=True)
        (1): Dropout(p=0, inplace=False)
        (2): GELU(approximate='none')
        (3): Linear(in_features=300, out_features=300,

In [29]:
estimator.model_list_[0].ft_base.parameters()

<generator object Module.parameters at 0x32a1a5700>